// editor/client_solid/src/routes/Test.js
import React, { useState, useEffect } from 'react';
import { useHistory, useParams } from 'react-router-dom';

import Iframe from 'react-iframe'

import getData from "../helpers/getData";
import '../css/Test.css';


function Test() {
    const history = useHistory();

    const { room_url } = useParams();
    const [roles, setRoles] = useState({});

    useEffect(() => {
        ////console.log('room_url', room_url);
        getData(`${props.url.fetch}/api/room/getRoleUrls/${room_url}`)
            .then(res => res.json())
            .then(res => {
                if (!res) return Promise.reject('errrr');
                ////console.log(res);
                setRoles(res.role_urls);
            })
            .catch(err => {

            });
    }, [room_url])

    return (<div className='flex-container'>
        {roles ? Object.entries(roles).map(([key, role_url]) =>
            <Iframe key={role_url} url={`${props.url.play}/${room_url}${role_url}/unsafe`}></Iframe>
        ) : null}
    </div>)
}

export default Test;

// editor/client_solid/src/routes/Test.jsx
import getData from "../helpers/getData";
import "../css/Test.css";

import { createSignal, For, onMount, createEffect } from "solid-js";
import { createStore } from "solid-js/store";
import { useParams } from "solid-app-router";

function Test(props) {
  // const history = useHistory();

  const { room_url } = useParams();
  //   const [getRoleUrls, setRoleUrls] = createSignal([]);
  let [state, setState] = createStore({ role_urls: undefined });

  onMount(() => {
    getData(`${props.urls.fetch}/api/room/getRoleUrls/${room_url}`)
      .then((res) => res.json())
      .then((res) => {
        if (!res) return Promise.reject("errrr");
        console.log(res.role_urls);
        console.log("state.role_urls", state.role_urls);
        setState("role_urls", res.role_urls);
        console.log("state.role_urls", state.role_urls);
      })
      .catch((err) => {});
  });

  createEffect(() => console.log(state.role_urls));

  return (
    <div className="flex-container">
      {
        <For each={state.role_urls}>
          {(role_url) => (
            <iframe
              src={`${props.urls.play}/${room_url}${role_url}/unsafe`}
            ></iframe>
          )}
        </For>
      }
    </div>
  );
}

export default Test;
