// play/solid_ionic/src/components/card/InstructionElement.js
import { createMemo, Show, For } from "solid-js";

import { useStore } from '../../store/Store';

const InstructionElement = props => {
  const [, { getTextStyles, getHighlightStyles }] = useStore();

  const text_styles = createMemo(() =>
    getTextStyles({
      element: props.element,
      swatches: props.swatches,
    }),
    [props.element, props.swatches]
  )

  const highlight_styles = () =>
    getHighlightStyles({ element: props.element, swatches: props.swatches });



  return (
    <>
      <div className="text-container" style={text_styles}>
        <For each={props.formatted_text}>
          {(instruction, index) => (
            <div key={index}>
              <Show when={instruction.type === 'normal'}>
                <span
                  style={text_styles}>
                  {instruction.content}
                </span>
              </Show>
              <Show when={instruction.type === 'choice'}>
                <div
                  style={{
                    // 'textAlign': highlight_styles()['align-items'],
                    // width: '100%',
                  }}>
                  <For each={instruction.content}>
                    {(choice, index) => (
                      <div key={index} /* style={{ ...highlight_styles() }} */>
                        <span
                          style={{
                            flex: 'none',
                          }}>
                          {choice}
                        </span>
                      </div>
                    )}
                  </For>
                </div>
              </Show>
            </div>
          )}
        </For>
      </div>
    </>
  );
};

export default InstructionElement;

// play/src/components/card/InstructionElement.tsx
import React from 'react';
import { Text, View } from 'react-native';
import { For, Show } from '../utils/solid-like-components';

import { useStore } from '../../store/Store';
import { DesignElementText, Instruction } from '../../../../types';

type InstructionElementProps = {
  instruction: Instruction;
  element: DesignElementText;
  masked: DesignElementText;
};

const InstructionElement = (props: InstructionElementProps) => {
  const [, actions] = useStore();

  if (props.instruction.type === 'video') {
    return;
  }

  return (
    <>
      <View>
        <For each={props.instruction.text}>
          {(instruction, index) => (
            <Show when={instruction.content.length > 0}>
              <View key={`${props.instruction.instruction_id}_${index}`}>
                <Show when={instruction.type === 'normal'}>
                  <Text
                    style={actions.getTextStyles({ element: props.element, masked: props.masked })}
                  >
                    {instruction.content}
                  </Text>
                </Show>
                <Show when={instruction.type === 'choice'}>
                  <View
                    style={{
                      display: 'flex',

                      // backgroundColor: "grey",
                      justifyContent: 'flex-end',
                      flexDirection: 'row',
                      flexWrap: 'wrap',
                    }}
                  >
                    <For each={instruction.content as string[]}>
                      {(choice, index2) => (
                        <Text
                          key={`${props.instruction.instruction_id}_${index}_${index2}`}
                          style={actions.getHighlightStyles({
                            element: props.element,
                            masked: props.masked,
                          })}
                        >
                          {choice}
                        </Text>
                      )}
                    </For>
                  </View>
                </Show>
              </View>
            </Show>
          )}
        </For>
      </View>
    </>
  );
};

export default InstructionElement;
