// play/src/components/card/InstructionElement.tsx
import React from 'react';
import { Text, View } from 'react-native';
import { For, Show } from '../utils/solid-like-components';

import { useStore } from '../../store/Store';
import { DesignElementText, Instruction } from '../../../../types';

type InstructionElementProps = {
  instruction: Instruction;
  element: DesignElementText;
  masked: DesignElementText;
};

const InstructionElement = (props: InstructionElementProps) => {
  const [, actions] = useStore();

  if (props.instruction.type === 'video') {
    return;
  }

  return (
    <>
      <View>
        <For each={props.instruction.text}>
          {(instruction, index) => (
            <Show when={instruction.content.length > 0}>
              <View key={`${props.instruction.instruction_id}_${index}`}>
                <Show when={instruction.type === 'normal'}>
                  <Text
                    style={actions.getTextStyles({ element: props.element, masked: props.masked })}
                  >
                    {instruction.content}
                  </Text>
                </Show>
                <Show when={instruction.type === 'choice'}>
                  <View
                    style={{
                      display: 'flex',

                      // backgroundColor: "grey",
                      justifyContent: 'flex-end',
                      flexDirection: 'row',
                      flexWrap: 'wrap',
                    }}
                  >
                    <For each={instruction.content as string[]}>
                      {(choice, index2) => (
                        <Text
                          key={`${props.instruction.instruction_id}_${index}_${index2}`}
                          style={actions.getHighlightStyles({
                            element: props.element,
                            masked: props.masked,
                          })}
                        >
                          {choice}
                        </Text>
                      )}
                    </For>
                  </View>
                </Show>
              </View>
            </Show>
          )}
        </For>
      </View>
    </>
  );
};

export default InstructionElement;

// card_editor/solid/src/components/card/InstructionElement.jsx
import {
  createSignal,
  For,
  createMemo,
  Switch,
  Match,
  createEffect,
} from "solid-js";

import { useStore } from "../../store/Store";

const TextElement = (props) => {
  const [state, actions] = useStore();

  const text_styles = createMemo(() =>
    actions.getTextStyles({
      element: props.element,
      swatches: props.swatches,
    })
  );

  const highlight_styles = createMemo(() =>
    actions.getHighlightStyles({
      element: props.element,
      swatches: props.swatches,
    })
  );

  return (
    <>
      <div className="text-container" style={text_styles()}>
        <For each={props.card_state.formatted_text}>
          {(instruction) => (
            <Switch>
              <Match when={instruction.type === "normal"}>
                <span
                  style={{
                    "text-align": text_styles()["align-items"],
                  }}
                >
                  {instruction.content}
                </span>
              </Match>
              <Match when={instruction.type === "choice"}>
                <div
                  style={{
                    "text-align": highlight_styles()["align-items"],
                    width: "100%",
                  }}
                >
                  <For each={instruction.content}>
                    {(choice) => (
                      <div style={{ ...highlight_styles() }}>
                        <span
                          style={{
                            flex: "none",
                          }}
                        >
                          {choice}
                        </span>
                      </div>
                    )}
                  </For>
                </div>
              </Match>
            </Switch>
          )}
        </For>
      </div>
    </>
  );
};

export default TextElement;
